{
    CONSTRUCTOR_ID: 2187439201,
    SUBCLASS_OF_ID: 3316604308,
    className: 'Channel',
    classType: 'constructor',
    flags: 1319360,
    creator: false,
    left: false,
    broadcast: false,
    verified: true,
    megagroup: true,
    restricted: false,
    signatures: false,
    min: false,
    scam: false,
    hasLink: true,
    hasGeo: false,
    slowmodeEnabled: false,
    callActive: false,
    callNotEmpty: false,
    fake: false,
    gigagroup: false,
    noforwards: false,
    id: Integer { value: 1136071376n },
    accessHash: Integer { value: 4550417351189372691n },
    title: '币安官方中文群',
    username: 'BinanceChinese',
    photo: {
      CONSTRUCTOR_ID: 476978193,
      SUBCLASS_OF_ID: 2889794789,
      className: 'ChatPhoto',
      classType: 'constructor',
      flags: 2,
      hasVideo: false,
      photoId: [Integer],
      strippedThumb: <Buffer 01 08 08 d7 fe 3e f4 51 45 24 07>,
      dcId: 5
    },
    date: 1632898598,
    restrictionReason: null,
    adminRights: null,
    bannedRights: null,
    defaultBannedRights: {
      CONSTRUCTOR_ID: 2668758040,
      SUBCLASS_OF_ID: 1263814057,
      className: 'ChatBannedRights',
      classType: 'constructor',
      flags: 165120,
      viewMessages: false,
      sendMessages: false,
      sendMedia: false,
      sendStickers: false,
      sendGifs: false,
      sendGames: false,
      sendInline: false,
      embedLinks: false,
      sendPolls: true,
      changeInfo: true,
      inviteUsers: true,
      pinMessages: true,
      untilDate: 2147483647
    },
    participantsCount: null
  }
}