{
  CONSTRUCTOR_ID: 940666592,
  SUBCLASS_OF_ID: 2030045667,
  className: 'Message',
  classType: 'constructor',
  out: false,
  mentioned: false,
  mediaUnread: false,
  silent: false,
  post: false,
  fromScheduled: false,
  legacy: false,
  editHide: false,
  ttlPeriod: null,
  id: 2749134,
  fromId: {
    CONSTRUCTOR_ID: 1498486562,
    SUBCLASS_OF_ID: 47470215,
    className: 'PeerUser',
    classType: 'constructor',
    userId: Integer { value: 5403522381n }
  },
  peerId: {
    CONSTRUCTOR_ID: 2728736542,
    SUBCLASS_OF_ID: 47470215,
    className: 'PeerChannel',
    classType: 'constructor',
    channelId: Integer { value: 1119054974n }
  },
  fwdFrom: null,
  viaBotId: null,
  replyTo: null,
  date: 1655050549,
  message: 'hi',
  media: null,
  replyMarkup: null,
  entities: null,
  views: null,
  forwards: null,
  replies: {
    CONSTRUCTOR_ID: 2211844034,
    SUBCLASS_OF_ID: 1825397986,
    className: 'MessageReplies',
    classType: 'constructor',
    flags: 0,
    comments: false,
    replies: 0,
    repliesPts: 4138413,
    recentRepliers: null,
    channelId: null,
    maxId: null,
    readMaxId: null
  },
  editDate: null,
  pinned: false,
  postAuthor: null,
  groupedId: null,
  restrictionReason: null,
  action: undefined,
  noforwards: false,
  reactions: null,
  flags: 8388864
}